services:
  ihaskell-notebook:
    platform: linux/arm64/v8          # native on Apple Silicon (no emulation)
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      # Your notebooks live here inside the container
      - ./notebook:/root/work
    restart: unless-stopped