version: '3.3'

services:
   ihaskell-notebook:
     build: .
     ports:
       - "9888:9888"
     volumes:
       - ./notebook:/home/jovyan/work
     restart: unless-stopped
     environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: x

